version: '3'

# CREATE SERVICES
services:
  # WEB SERVER
  webserver:
    container_name: 'newspaper-backend-webserver'
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # CREATE APP
  app:
    container_name: 'newspaper-backend-app'
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - .env.docker:/var/www/html/.env
    depends_on:
      - php
      - db
    networks:
      - laravel

  # CREATE DB
  db:
    container_name: 'newspaper-backend-db'
    image: mysql:8.0.32
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=newspaper
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - laravel
  
  # CREATE PHP
  php:
    container_name: 'newspaper-backend-php'
    image: php:8.1.15-fpm
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel
      
# CREATE NETWORKS
networks:
  laravel:
    driver: bridge
